
CICADA_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

ERMIA_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

MOCC_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

SI_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

SILO_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

SS2PL_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

TICTOC_SRCS1+=\
$(REL)result.cc\
$(REL)util.cc\

######
INST_SRCS1+=\
$(REL)util.cc

INST_SRCS2+=\
$(REL)util.cc

INST_SRCS3+=\
$(REL)util.cc

INST_SRCS4+=\
$(REL)util.cc
######
