include(CompileOptions)
include(Options)

# ccbench_add_protocol(<name>
#   SOURCES   <protocol .cc files shared by every workload binary>
#   WORKLOADS <workload tags...>            # e.g. ycsb tpcc bomb sbomb
#   [OPTIONS  <KEY=VALUE>...]               # protocol-specific defines
# )
#
# For each workload tag W, builds an executable `W_<name>.exe` from
# `W_<name>.cc` plus the SOURCES list, links against ccbench_common +
# masstree + mimalloc, and applies:
#   - the universal CCBENCH_* defaults (KEY_SIZE, BACK_OFF, etc.)
#   - the protocol-specific OPTIONS (entries with empty VALUE are skipped,
#     mimicking the old `remove_definitions` path).
#
# Replaces the per-protocol boilerplate that used to be ~120 lines of
# file(GLOB) / add_executable / target_link_libraries / add_definitions.
function(ccbench_add_protocol name)
  set(opts "")
  set(one_value "")
  set(multi_value "SOURCES;WORKLOADS;OPTIONS")
  cmake_parse_arguments(P "${opts}" "${one_value}" "${multi_value}" ${ARGN})

  if(NOT P_WORKLOADS)
    message(FATAL_ERROR "ccbench_add_protocol(${name}): WORKLOADS is required")
  endif()

  ccbench_universal_definitions(_universal_defs)
  ccbench_normalize_options(_extra_defs ${P_OPTIONS})

  foreach(wl IN LISTS P_WORKLOADS)
    set(target "${wl}_${name}.exe")
    add_executable(${target} ${wl}_${name}.cc ${P_SOURCES})

    target_link_libraries(${target} PRIVATE
      ccbench_common
      ccbench::masstree
      ccbench::mimalloc)

    target_compile_definitions(${target} PRIVATE
      ${_universal_defs}
      ${_extra_defs})

    # Phased -Werror cleanup (see #43). The full -Wall -Wextra -Werror via
    # set_compile_options() is still gated on Phase 5 — we promote one
    # warning class to error at a time as the existing offenders get
    # fixed. Append the next entry here when its source-level cleanup
    # PR lands.
    target_compile_options(${target} PRIVATE
      -Werror=maybe-uninitialized
      -Werror=unused-but-set-variable
      -Werror=unused-label
      -Werror=reorder
      -Werror=unused-parameter
      -Werror=catch-value
      -Werror=unused-variable
      -Werror=ignored-qualifiers
      -Werror=sign-compare)

    set_property(TARGET ${target} PROPERTY CCBENCH_PROTOCOL "${name}")
    set_property(TARGET ${target} PROPERTY CCBENCH_WORKLOAD "${wl}")
  endforeach()

  # Record this protocol's row so the top-level CMakeLists can dump the
  # support matrix to PROTOCOL_MATRIX.md without manual sync. We use two
  # GLOBAL properties (an ordered list of names + one property per name)
  # rather than a single CSV row, because CMake flattens nested lists
  # when APPENDing a "a;b" value into a GLOBAL property list.
  set_property(GLOBAL APPEND PROPERTY CCBENCH_PROTOCOL_NAMES "${name}")
  set_property(GLOBAL PROPERTY CCBENCH_PROTOCOL_WORKLOADS_${name}
    "${P_WORKLOADS}")
endfunction()

# Write a Markdown table of every (protocol, workload) registered via
# ccbench_add_protocol(...) to ${out_path}. Columns mirror what
# CLAUDE.md / docs/protocols.md show: ycsb / tpcc / bomb / sbomb+dbomb.
# Workloads not in that fixed set still appear as extra columns.
function(ccbench_write_protocol_matrix out_path)
  get_property(_names GLOBAL PROPERTY CCBENCH_PROTOCOL_NAMES)
  if(NOT _names)
    return()
  endif()

  # Collect the unique workload tags actually used.
  set(_known_cols ycsb tpcc bomb sbomb dbomb)
  set(_seen_cols "")
  foreach(_name IN LISTS _names)
    get_property(_wls GLOBAL PROPERTY CCBENCH_PROTOCOL_WORKLOADS_${_name})
    list(APPEND _seen_cols ${_wls})
  endforeach()
  list(REMOVE_DUPLICATES _seen_cols)

  # Preserve _known_cols ordering, then append anything unexpected.
  set(_cols "")
  foreach(_c IN LISTS _known_cols)
    if(_c IN_LIST _seen_cols)
      list(APPEND _cols "${_c}")
    endif()
  endforeach()
  foreach(_c IN LISTS _seen_cols)
    if(NOT _c IN_LIST _known_cols)
      list(APPEND _cols "${_c}")
    endif()
  endforeach()

  set(_md "# Protocol × workload support matrix\n\n")
  string(APPEND _md "Auto-generated by `ccbench_write_protocol_matrix()`\n")
  string(APPEND _md "from each `cc/<protocol>/CMakeLists.txt`. Re-run\n")
  string(APPEND _md "`cmake -S . -B build` after editing a protocol's\n")
  string(APPEND _md "`WORKLOADS` list to refresh this file.\n\n")
  string(APPEND _md "| Protocol |")
  foreach(_c IN LISTS _cols)
    string(APPEND _md " ${_c} |")
  endforeach()
  string(APPEND _md "\n|---|")
  foreach(_c IN LISTS _cols)
    string(APPEND _md ":-:|")
  endforeach()
  string(APPEND _md "\n")

  foreach(_name IN LISTS _names)
    get_property(_wls GLOBAL PROPERTY CCBENCH_PROTOCOL_WORKLOADS_${_name})
    string(APPEND _md "| `cc/${_name}/` |")
    foreach(_c IN LISTS _cols)
      if(_c IN_LIST _wls)
        string(APPEND _md " ✓ |")
      else()
        string(APPEND _md " — |")
      endif()
    endforeach()
    string(APPEND _md "\n")
  endforeach()

  file(WRITE "${out_path}" "${_md}")
  message(STATUS "Wrote protocol×workload matrix to ${out_path}")
endfunction()
